### ISSUE TITLE
Working Directory

### ISSUE THREAD

**Issue by chances** [jerryjvl/jekyll-build-action#3]
How can I set the working directory?

If not supported, consider supporting something like this:

```yaml
- name: Build
  uses: jerryjvl/jekyll-build-action@v1
  with:
    working-directory: blog
```
